version: 2
updates:
- package-ecosystem: npm
  directory: "/frontendui"
  schedule:
    interval: daily
    time: "23:30"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
    timezone: Asia/Calcutta
  open-pull-requests-limit: 10
