runtime: python37
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker -b :$PORT --chdir ./WebBackendEngine server:app

handlers:
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301
