name: GAE Deploy

on:
  push:
    branches:
      - master

jobs:
  setup-build-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup and configure gcloud CLI
      - name: GAE Setup
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '290.0.1'
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS}}
      
      - name: Download Models
        run: |
          wget ${{ secrets.MODEL_URL }}
          mkdir -p ./WebBackendEngine/models
          mv models.zip ./WebBackendEngine/models
      
      - name: Unzip
        run: |
          unzip ./WebBackendEngine/models/models.zip
          
      # Deploy App to App Engine
      - name: Deploy
        run: |
          gcloud app deploy --quiet
